### ISSUE TITLE
Trying to update a resolved AffectedComponent's description results in error

### ISSUE THREAD

**Issue by gabehollombe** [gaqzi/incident-commander#31]
```
Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
    at AffectedSystems._update (affected-systems.mjs:119:12)
    at EventListeners.notify (event-bus.mjs:65:54)
    at EventDispatcher._dispatch (event-bus.mjs:113:20)
    at event-bus.mjs:86:16
    at Array.forEach (<anonymous>)
    at event-bus.mjs:85:23
    at Array.forEach (<anonymous>)
    at Array.<anonymous> (event-bus.mjs:83:36)
    at Object.callAll (function.js:19:12)
    at callEventHandlerListeners (EventHandler.js:87:5)
```

**Comment by gabehollombe** [comment]
Unable to repro. Think this got fixed in the rewrite to React + Typescript
